package com.heip.Cuida;

import static com.codename1.ui.CN.*;
import com.codename1.l10n.L10NManager;
import com.codename1.ui.plaf.UIManager;
import java.util.Hashtable;
import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;
import com.codename1.ui.plaf.*;
import com.codename1.ui.util.Resources;
import com.heip.Cuida.controllers.ConnectionController;
import com.heip.Cuida.controllers.HomeController;
import com.heip.Cuida.models.AuthCallback;
import com.heip.Cuida.models.AuthService;
import com.heip.Cuida.views.HomeView;
import com.heip.Cuida.views.LoginView;
import com.heip.Cuida.views.SignupView;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class Cuida extends Lifecycle {
  @Override
  public void init(Object context) {
    super.init(context);

    if (CN.isSimulator()) {
      Log.setLevel(Log.DEBUG);
    } else {
      Log.setLevel(Log.REPORTING_NONE);
    }
    UIManager.initFirstTheme("/theme");
    String language = L10NManager.getInstance().getLanguage();
    Resources global = Resources.getGlobalResources();
    Hashtable<String, String> bundle = global == null ? null : global.getL10N("messages", language);
    if (bundle == null && global != null) {
      bundle = global.getL10N("messages", "");
    }
    if (bundle != null) {
      UIManager.getInstance().setBundle(bundle);
    }
  }

  @Override
  public void runApp() {
    String token = Preferences.get("jwt_session_token", null);
    String userId = Preferences.get("current_user_id", null);

    if (token != null && !token.isEmpty() && userId != null) {
      AuthService authService = new AuthService();
      authService.fecthProfile(userId, new AuthCallback() {
        @Override
        public void onSuccess(String message) {
          Log.p("Auto-login thành công cho user: " + userId, Log.INFO);
          
          HomeView homeView = new HomeView();
          new HomeController(homeView);
          homeView.show();
          }
        @Override
        public void onFailure(String error) {
          Log.p("Auto-login thất bại: " + error, Log.WARNING);
          
          Preferences.set("jwt_session_token", null);
          Preferences.set("current_user_id", null);
          
          openLoginScreen();
        }
      });
      return;
    }
    openLoginScreen();
  }

  public void openLoginScreen() {
    LoginView loginView = new LoginView();
    SignupView signupView = new SignupView();
    ConnectionController connectionController = new ConnectionController(signupView, loginView);
    loginView.show();
  }
}
