package com.heip.Cuida;

import static com.codename1.ui.CN.*;
import com.codename1.l10n.L10NManager;
import com.codename1.ui.plaf.UIManager;
import java.util.Hashtable;
import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;
import com.codename1.ui.plaf.*;
import com.codename1.ui.util.Resources;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class Cuida extends Lifecycle {
    @Override
    public void init(Object context) {
        super.init(context);
        String language = L10NManager.getInstance().getLanguage();
        Resources global = Resources.getGlobalResources();
        Hashtable<String, String> bundle = global == null ? null : global.getL10N("messages", language);
        if (bundle == null && global != null) {
            bundle = global.getL10N("messages", "");
        }
        if (bundle != null) {
            UIManager.getInstance().setBundle(bundle);
        }
    }


    @Override
    public void runApp() {
        Form hi = new Form("Hi World", BoxLayout.y());
        Button helloButton = new Button("Hello World");
        hi.add(helloButton);
        helloButton.addActionListener(e -> hello());
        hi.getToolbar().addMaterialCommandToSideMenu("Hello Command",
        FontImage.MATERIAL_CHECK, 4, e -> hello());
        hi.show();
    }

    private void hello() {
        Dialog.show("Hello Codename One", "Welcome to Codename One", "OK", null);
    }

}
